In [14]:
import pandas as pd
a=pd.read_csv("rahul.csv")
a.head()
a["Variable_code"]
a["rahul"]="rahul rathore best"
a["rahul"]
a.insert(1,column="rahul1",value="r")
a.head(10)

,Year,rahul1,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06,rahul
0,2017,r,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,644159,ANZSIC06 divisions A-S (excluding classes K633...,rahul rathore best
1,2017,r,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,567080,ANZSIC06 divisions A-S (excluding classes K633...,rahul rathore best
2,2017,r,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,59317,ANZSIC06 divisions A-S (excluding classes K633...,rahul rathore best
3,2017,r,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,17762,ANZSIC06 divisions A-S (excluding classes K633...,rahul rathore best
4,2017,r,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,560665,ANZSIC06 divisions A-S (excluding classes K633...,rahul rathore best
5,2017,r,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,33474,ANZSIC06 divisions A-S (excluding classes K633...,rahul rathore best
6,2017,r,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,6890,ANZSIC06 divisions A-S (excluding classes K633...,rahul rathore best
7,2017,r,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,18730,ANZSIC06 divisions A-S (excluding classes K633...,rahul rathore best
8,2017,r,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,99874,ANZSIC06 divisions A-S (excluding classes K633...,rahul rathore best
9,2017,r,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,226,ANZSIC06 divisions A-S (excluding classes K633...,rahul rathore best